[package]
edition.workspace = true
version.workspace = true
authors.workspace = true
name = "znp_types"

[dependencies]
znp_macros.workspace = true

enumflags2.workspace = true
thiserror.workspace = true
log.workspace = true

bincode = "2.0.0-rc.3"
