#[derive(num_derive::FromPrimitive)]
#[repr(u8)]
#[derive(Debug, Clone, Copy)]
pub enum Status {
    Success = 0x00,

    Failure = 0x01,
    InvalidParameter = 0x02,
    InvalidTask = 0x03,
    MsgBufferNotAvail = 0x04,
    InvalidMsgPointer = 0x05,
    InvalidEventId = 0x06,
    InvalidInterruptId = 0x07,
    NoTimerAvail = 0x08,
    NvItemUninit = 0x09,
    NvOperFailed = 0x0A,
    InvalidMemSize = 0x0B,
    NvBadItemLen = 0x0C,
    MemError = 0x10,
    BufferFull = 0x11,
    UnsupportedMode = 0x12,
    MacMemError = 0x13,

    SapiInProgress = 0x20,
    SapiTimeout = 0x21,
    SapiInit = 0x22,

    NotAuthorized = 0x7E,

    MalformedCmd = 0x80,
    UnsupClusterCmd = 0x81,

    OtaAbort = 0x95,
    OtaImageInvalid = 0x96,
    OtaWaitForData = 0x97,
    OtaNoImageAvailable = 0x98,
    OtaRequireMoreImage = 0x99,

    ApsFail = 0xB1,
    ApsTableFull = 0xB2,
    ApsIllegalRequest = 0xB3,
    ApsInvalidBinding = 0xB4,
    ApsUnsupportedAttrib = 0xB5,
    ApsNotSupported = 0xB6,
    ApsNoAck = 0xB7,
    ApsDuplicateEntry = 0xB8,
    ApsNoBoundDevice = 0xB9,
    ApsNotAllowed = 0xBA,
    ApsNotAuthenticated = 0xBB,

    SecNoKey = 0xA1,
    SecOldFrmCount = 0xA2,
    SecMaxFrmCount = 0xA3,
    SecCcmFail = 0xA4,
    SecFailure = 0xAD,

    NwkInvalidParam = 0xC1,
    NwkInvalidRequest = 0xC2,
    NwkNotPermitted = 0xC3,
    NwkStartupFailure = 0xC4,
    NwkAlreadyPresent = 0xC5,
    NwkSyncFailure = 0xC6,
    NwkTableFull = 0xC7,
    NwkUnknownDevice = 0xC8,
    NwkUnsupportedAttribute = 0xC9,
    NwkNoNetworks = 0xCA,
    NwkLeaveUnconfirmed = 0xCB,
    NwkNoAck = 0xCC,
    NwkNoRoute = 0xCD,

    MacUnsupported = 0x18,
    MacBadState = 0x19,
    MacNoResources = 0x1A,
    MacAckPending = 0x1B,
    MacNoTime = 0x1C,
    MacTxAborted = 0x1D,
    MacDuplicatedEntry = 0x1E,
    MacCounterError = 0xDB,
    MacImproperKeyType = 0xDC,
    MacImproperSecurityLevel = 0xDD,
    MacUnsupportedLegacy = 0xDE,
    MacUnsupportedSecurity = 0xDF,
    MacBeaconLoss = 0xE0,
    MacChannelAccessFailure = 0xE1,
    MacDenied = 0xE2,
    MacDisableTrxFailure = 0xE3,
    MacSecurityError = 0xE4,
    MacFrameTooLong = 0xE5,
    MacInvalidGts = 0xE6,
    MacInvalidHandle = 0xE7,
    MacInvalidParameter = 0xE8,
    MacNoAck = 0xE9,
    MacNoBeacon = 0xEA,
    MacNoData = 0xEB,
    MacNoShortAddress = 0xEC,

    MacOutOfCap = 0xED,
    MacPanIdConflict = 0xEE,
    MacRealignment = 0xEF,
    MacTransactionExpired = 0xF0,
    MacTransactionOverflow = 0xF1,
    MacTxActive = 0xF2,
    MacUnavailableKey = 0xF3,
    MacUnsupportedAttribute = 0xF4,
    MacInvalidAddress = 0xF5,

    MacOnTimeTooLong = 0xF6,

    MacPastTime = 0xF7,
    MacTrackingOff = 0xF8,
    MacInvalidIndex = 0xF9,
    MacLimitReached = 0xFA,
    MacReadOnly = 0xFB,
    MacScanInProgress = 0xFC,
    MacSuperframeOverlap = 0xFD,
    MacAutoackPendingAllOn = 0xFE,
    MacAutoackPendingAllOff = 0xFF,
}
