[package]
edition.workspace = true
version.workspace = true
authors.workspace = true
name = "znp_macros"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
